### ISSUE TITLE
在ubuntu 20.04下编译失败

### ISSUE THREAD

**Issue by codercaizh** [hanwckf/bl-mt798x#11]
![image](https://github.com/hanwckf/bl-mt798x/assets/17381647/7776dfd9-12df-445f-9d5f-80799da81a68)
commitId：567c8151fcdfc0b5c0be4f5cf70e42ac0def6c14
命令： SOC=mt7981 BOARD=360t7 ./build.sh
环境：hyper-V下的x86 ubuntu 20.04
编译报这个错，也没有生成output目录，已按照要求安装依赖，不知道是我哪里弄错？

**Comment by hanwckf** [comment]
把完整的日志输出发上来

**Comment by codercaizh** [comment]
> 把完整的日志输出发上来
`caizh@ubuntu2004:~/bl-mt798x$ SOC=mt7981 BOARD=360t7 ./build.sh
Trying cross compiler...
/usr/bin/aarch64-linux-gnu-gcc
Building for CPU: mt7981, BOARD: 360t7, fixed-mtdparts: 1, multi-layout: 0
Build u-boot...
Build u-boot with fixed-mtdparts!
make: Entering directory '/home/caizh/bl-mt798x/uboot-mtk-20220606'
scripts/kconfig/conf  --olddefconfig Kconfig
#
# configuration written to .config
#
scripts/kconfig/conf  --syncconfig Kconfig
  CFG     u-boot.cfg
  GEN     include/autoconf.mk
  GEN     include/autoconf.mk.dep
===================== WARNING ======================
CONFIG_OF_EMBED is enabled. This option should only
be used for debugging purposes. Please use
CONFIG_OF_SEPARATE for boards in mainline.
See doc/develop/devicetree/control.rst for more info.
====================================================
  CFGCHK  u-boot.cfg
  OFCHK   .config
  UPD     include/generated/timestamp_autogenerated.h
  ENVC    include/generated/env.txt
  ENVP    include/generated/env.in
  ENVT    include/generated/environment.h
  CC      cmd/version.o
  AR      cmd/built-in.o
  CC      env/common.o
  AR      env/built-in.o
  CC      failsafe/fs.o
  AR      failsafe/built-in.o
  LD      u-boot
  OBJCOPY u-boot.srec
  SYM     u-boot.sym
  OBJCOPY u-boot-nodtb.bin
  RELOC   u-boot-nodtb.bin
  COPY    u-boot.bin
  MKIMAGE u-boot-mtk.bin
make: Leaving directory '/home/caizh/bl-mt798x/uboot-mtk-20220606'
u-boot build done!
Build atf...
make: Entering directory '/home/caizh/bl-mt798x/atf-20220606-637ba581b'
>> Unable to find python
>> You must have python installed in order
>> to use 'make menuconfig'
make: *** [makefile:145: check_python] Error 1
make: Leaving directory '/home/caizh/bl-mt798x/atf-20220606-637ba581b'
make: Entering directory '/home/caizh/bl-mt798x/atf-20220606-637ba581b'
make -f /home/caizh/bl-mt798x/atf-20220606-637ba581b/Makefile CONFIG_CROSS_COMPILER=aarch64-linux-gnu- clean
make[1]: Entering directory '/home/caizh/bl-mt798x/atf-20220606-637ba581b'
  CLEAN
make[1]: Leaving directory '/home/caizh/bl-mt798x/atf-20220606-637ba581b'
make: Leaving directory '/home/caizh/bl-mt798x/atf-20220606-637ba581b'
make: Entering directory '/home/caizh/bl-mt798x/atf-20220606-637ba581b'
make -f /home/caizh/bl-mt798x/atf-20220606-637ba581b/Makefile CONFIG_CROSS_COMPILER=aarch64-linux-gnu- all
make[1]: Entering directory '/home/caizh/bl-mt798x/atf-20220606-637ba581b'
  CC      lib/libfdt/fdt.c
  CC      lib/libfdt/fdt_addresses.c
  CC      lib/libfdt/fdt_empty_tree.c
  CC      lib/libfdt/fdt_ro.c
  CC      lib/libfdt/fdt_rw.c
  CC      lib/libfdt/fdt_strerror.c
  CC      lib/libfdt/fdt_sw.c
  CC      lib/libfdt/fdt_wip.c
  AR      /home/caizh/bl-mt798x/atf-20220606-637ba581b/build/fvp/release/lib/libfdt.a
Building fvp
  CC      lib/libc/abort.c
  CC      lib/libc/assert.c
  CC      lib/libc/exit.c
  CC      lib/libc/memchr.c
  CC      lib/libc/memcmp.c
  CC      lib/libc/memcpy.c
  CC      lib/libc/memmove.c
  CC      lib/libc/memrchr.c
  CC      lib/libc/printf.c
  CC      lib/libc/putchar.c
  CC      lib/libc/puts.c
  CC      lib/libc/snprintf.c
  CC      lib/libc/strchr.c
  CC      lib/libc/strcmp.c
  CC      lib/libc/strlcat.c
  CC      lib/libc/strlcpy.c
  CC      lib/libc/strlen.c
  CC      lib/libc/strncmp.c
  CC      lib/libc/strnlen.c
  CC      lib/libc/strrchr.c
  CC      lib/libc/strtok.c
  CC      lib/libc/strtoul.c
  CC      lib/libc/strtoll.c
  CC      lib/libc/strtoull.c
  CC      lib/libc/strtol.c
  AS      lib/libc/aarch64/memset.S
  AS      lib/libc/aarch64/setjmp.S
  AR      /home/caizh/bl-mt798x/atf-20220606-637ba581b/build/fvp/release/lib/libc.a
  CC      bl1/aarch64/bl1_arch_setup.c
  CC      bl1/aarch64/bl1_context_mgmt.c
  CC      bl1/bl1_main.c
  CC      common/fdt_wrappers.c
  CC      common/uuid.c
  CC      drivers/arm/cci/cci.c
  CC      drivers/arm/smmu/smmu_v3.c
  CC      drivers/arm/sp805/sp805.c
  CC      drivers/cfi/v2m/v2m_flash.c
  CC      drivers/delay_timer/delay_timer.c
  CC      drivers/delay_timer/generic_delay_timer.c
  CC      drivers/io/io_fip.c
  CC      drivers/io/io_memmap.c
  CC      drivers/io/io_semihosting.c
  CC      drivers/io/io_storage.c
  CC      lib/cpus/errata_report.c
  CC      lib/el3_runtime/aarch64/context_mgmt.c
  CC      lib/fconf/fconf.c
  CC      lib/fconf/fconf_dyn_cfg_getter.c
  CC      lib/semihosting/semihosting.c
  CC      plat/arm/board/fvp/fvp_bl1_setup.c
  CC      plat/arm/board/fvp/fvp_err.c
  CC      plat/arm/board/fvp/fvp_io_storage.c
  CC      plat/arm/common/arm_bl1_setup.c
  CC      plat/arm/common/arm_dyn_cfg.c
  CC      plat/arm/common/arm_dyn_cfg_helpers.c
  CC      plat/arm/common/arm_err.c
  CC      plat/arm/common/arm_io_storage.c
  CC      plat/arm/common/fconf/arm_fconf_io.c
  CC      plat/common/plat_bl1_common.c
  CC      common/bl_common.c
  CC      common/tf_log.c
  CC      drivers/console/multi_console.c
  CC      plat/common/plat_bl_common.c
  CC      plat/common/plat_log_common.c
  CC      plat/common/aarch64/plat_common.c
  CC      lib/compiler-rt/builtins/popcountdi2.c
  CC      lib/compiler-rt/builtins/popcountsi2.c
  CC      plat/arm/board/fvp/fvp_common.c
  CC      plat/arm/common/arm_common.c
  CC      plat/arm/common/arm_console.c
  CC      lib/xlat_tables_v2/aarch64/xlat_tables_arch.c
  CC      lib/xlat_tables_v2/xlat_tables_context.c
  CC      lib/xlat_tables_v2/xlat_tables_core.c
  CC      lib/xlat_tables_v2/xlat_tables_utils.c
  AS      bl1/aarch64/bl1_entrypoint.S
  AS      bl1/aarch64/bl1_exceptions.S
  AS      lib/cpus/aarch64/aem_generic.S
  AS      lib/cpus/aarch64/cortex_a35.S
  AS      lib/cpus/aarch64/cortex_a53.S
  AS      lib/cpus/aarch64/cortex_a57.S
  AS      lib/cpus/aarch64/cortex_a72.S
  AS      lib/cpus/aarch64/cortex_a73.S
  AS      lib/cpus/aarch64/cpu_helpers.S
  AS      lib/cpus/aarch64/dsu_helpers.S
  AS      lib/el3_runtime/aarch64/context.S
  AS      lib/semihosting/aarch64/semihosting_call.S
  AS      plat/arm/board/fvp/aarch64/fvp_helpers.S
  AS      plat/common/aarch64/platform_up_stack.S
  AS      common/aarch64/debug.S
  AS      lib/aarch64/cache_helpers.S
  AS      lib/aarch64/misc_helpers.S
  AS      plat/common/aarch64/platform_helpers.S
  AS      drivers/arm/pl011/aarch64/pl011_console.S
  AS      plat/arm/board/common/aarch64/board_arm_helpers.S
  AS      plat/arm/common/aarch64/arm_helpers.S
  AS      lib/xlat_tables_v2/aarch64/enable_mmu.S
  PP      bl1/bl1.ld.S
  LD      /home/caizh/bl-mt798x/atf-20220606-637ba581b/build/fvp/release/bl1/bl1.elf
  BIN     /home/caizh/bl-mt798x/atf-20220606-637ba581b/build/fvp/release/bl1.bin

Built /home/caizh/bl-mt798x/atf-20220606-637ba581b/build/fvp/release/bl1.bin successfully

  OD      /home/caizh/bl-mt798x/atf-20220606-637ba581b/build/fvp/release/bl1/bl1.dump
  CC      bl2/aarch64/bl2_arch_setup.c
  CC      bl2/bl2_image_load_v2.c
  CC      bl2/bl2_main.c
  CC      common/desc_image_load.c
  CC      common/fdt_wrappers.c
  CC      common/tf_crc32.c
  CC      common/uuid.c
  CC      drivers/arm/sp805/sp805.c
  CC      drivers/arm/tzc/tzc400.c
  CC      drivers/cfi/v2m/v2m_flash.c
  CC      drivers/delay_timer/delay_timer.c
  CC      drivers/delay_timer/generic_delay_timer.c
  CC      drivers/io/io_fip.c
  CC      drivers/io/io_memmap.c
  CC      drivers/io/io_semihosting.c
  CC      drivers/io/io_storage.c
  CC      lib/fconf/fconf.c
  CC      lib/fconf/fconf_dyn_cfg_getter.c
  CC      lib/semihosting/semihosting.c
  CC      lib/utils/mem_region.c
  CC      plat/arm/board/fvp/fvp_bl2_setup.c
  CC      plat/arm/board/fvp/fvp_err.c
  CC      plat/arm/board/fvp/fvp_io_storage.c
  CC      plat/arm/board/fvp/fvp_security.c
  CC      plat/arm/common/aarch64/arm_bl2_mem_params_desc.c
  CC      plat/arm/common/arm_bl2_setup.c
  CC      plat/arm/common/arm_dyn_cfg.c
  CC      plat/arm/common/arm_dyn_cfg_helpers.c
  CC      plat/arm/common/arm_err.c
  CC      plat/arm/common/arm_image_load.c
  CC      plat/arm/common/arm_io_storage.c
  CC      plat/arm/common/arm_nor_psci_mem_protect.c
  CC      plat/arm/common/arm_tzc400.c
  CC      plat/arm/common/fconf/arm_fconf_io.c
  CC      common/bl_common.c
  CC      common/tf_log.c
  CC      drivers/console/multi_console.c
  CC      plat/common/plat_bl_common.c
  CC      plat/common/plat_log_common.c
  CC      plat/common/aarch64/plat_common.c
  CC      lib/compiler-rt/builtins/popcountdi2.c
  CC      lib/compiler-rt/builtins/popcountsi2.c
  CC      plat/arm/board/fvp/fvp_common.c
  CC      plat/arm/common/arm_common.c
  CC      plat/arm/common/arm_console.c
  CC      lib/xlat_tables_v2/aarch64/xlat_tables_arch.c
  CC      lib/xlat_tables_v2/xlat_tables_context.c
  CC      lib/xlat_tables_v2/xlat_tables_core.c
  CC      lib/xlat_tables_v2/xlat_tables_utils.c
  AS      bl2/aarch64/bl2_entrypoint.S
  AS      common/aarch64/early_exceptions.S
  AS      lib/locks/exclusive/aarch64/spinlock.S
  AS      lib/semihosting/aarch64/semihosting_call.S
  AS      plat/common/aarch64/platform_up_stack.S
  AS      common/aarch64/debug.S
  AS      lib/aarch64/cache_helpers.S
  AS      lib/aarch64/misc_helpers.S
  AS      plat/common/aarch64/platform_helpers.S
  AS      drivers/arm/pl011/aarch64/pl011_console.S
  AS      plat/arm/board/common/aarch64/board_arm_helpers.S
  AS      plat/arm/common/aarch64/arm_helpers.S
  AS      lib/xlat_tables_v2/aarch64/enable_mmu.S
  PP      bl2/bl2.ld.S
  LD      /home/caizh/bl-mt798x/atf-20220606-637ba581b/build/fvp/release/bl2/bl2.elf
  BIN     /home/caizh/bl-mt798x/atf-20220606-637ba581b/build/fvp/release/bl2.bin

Built /home/caizh/bl-mt798x/atf-20220606-637ba581b/build/fvp/release/bl2.bin successfully

  OD      /home/caizh/bl-mt798x/atf-20220606-637ba581b/build/fvp/release/bl2/bl2.dump
  CC      bl31/bl31_context_mgmt.c
  CC      bl31/bl31_main.c
  CC      bl31/interrupt_mgmt.c
  CC      common/fdt_wrappers.c
  CC      common/runtime_svc.c
  CC      drivers/arm/cci/cci.c
  CC      drivers/arm/fvp/fvp_pwrc.c
  CC      drivers/arm/gic/v3/gic-x00.c
  CC      drivers/arm/gic/v3/gicdv3_helpers.c
  CC      drivers/arm/gic/v3/gicrv3_helpers.c
  CC      drivers/arm/gic/v3/gicv3_helpers.c
  CC      drivers/arm/gic/v3/gicv3_main.c
  CC      drivers/arm/smmu/smmu_v3.c
  CC      drivers/arm/tzc/tzc400.c
  CC      drivers/cfi/v2m/v2m_flash.c
  CC      drivers/delay_timer/delay_timer.c
  CC      drivers/delay_timer/generic_delay_timer.c
  CC      lib/cpus/aarch64/cpuamu.c
  CC      lib/cpus/errata_report.c
  CC      lib/el3_runtime/aarch64/context_mgmt.c
  CC      lib/el3_runtime/cpu_data_array.c
  CC      lib/extensions/amu/aarch64/amu.c
  CC      lib/extensions/brbe/brbe.c
  CC      lib/extensions/spe/spe.c
  CC      lib/extensions/sve/sve.c
  CC      lib/extensions/sys_reg_trace/aarch64/sys_reg_trace.c
  CC      lib/extensions/trbe/trbe.c
  CC      lib/extensions/trf/aarch64/trf.c
  CC      lib/fconf/fconf.c
  CC      lib/fconf/fconf_dyn_cfg_getter.c
  CC      lib/locks/bakery/bakery_lock_coherent.c
  CC      lib/pmf/pmf_main.c
  CC      lib/pmf/pmf_smc.c
  CC      lib/psci/psci_common.c
  CC      lib/psci/psci_main.c
  CC      lib/psci/psci_mem_protect.c
  CC      lib/psci/psci_off.c
  CC      lib/psci/psci_on.c
  CC      lib/psci/psci_setup.c
  CC      lib/psci/psci_stat.c
  CC      lib/psci/psci_suspend.c
  CC      lib/psci/psci_system_off.c
  CC      lib/utils/mem_region.c
  CC      plat/arm/board/fvp/fconf/fconf_hw_config_getter.c
  CC      plat/arm/board/fvp/fvp_bl31_setup.c
  CC      plat/arm/board/fvp/fvp_console.c
  CC      plat/arm/board/fvp/fvp_gicv3.c
  CC      plat/arm/board/fvp/fvp_pm.c
  CC      plat/arm/board/fvp/fvp_security.c
  CC      plat/arm/board/fvp/fvp_topology.c
  CC      plat/arm/common/aarch64/execution_state_switch.c
  CC      plat/arm/common/arm_bl31_setup.c
  CC      plat/arm/common/arm_gicv3.c
  CC      plat/arm/common/arm_nor_psci_mem_protect.c
  CC      plat/arm/common/arm_pm.c
  CC      plat/arm/common/arm_sip_svc.c
  CC      plat/arm/common/arm_topology.c
  CC      plat/arm/common/arm_tzc400.c
  CC      plat/common/plat_gicv3.c
  CC      plat/common/plat_psci_common.c
  CC      services/arm_arch_svc/arm_arch_svc_setup.c
  CC      services/std_svc/std_svc_setup.c
  CC      common/bl_common.c
  CC      common/tf_log.c
  CC      drivers/console/multi_console.c
  CC      plat/common/plat_bl_common.c
  CC      plat/common/plat_log_common.c
  CC      plat/common/aarch64/plat_common.c
  CC      lib/compiler-rt/builtins/popcountdi2.c
  CC      lib/compiler-rt/builtins/popcountsi2.c
  CC      plat/arm/board/fvp/fvp_common.c
  CC      plat/arm/common/arm_common.c
  CC      plat/arm/common/arm_console.c
  CC      lib/xlat_tables_v2/aarch64/xlat_tables_arch.c
  CC      lib/xlat_tables_v2/xlat_tables_context.c
  CC      lib/xlat_tables_v2/xlat_tables_core.c
  CC      lib/xlat_tables_v2/xlat_tables_utils.c
  AS      bl31/aarch64/bl31_entrypoint.S
  AS      bl31/aarch64/crash_reporting.S
  AS      bl31/aarch64/ea_delegate.S
  AS      bl31/aarch64/runtime_exceptions.S
  AS      lib/cpus/aarch64/aem_generic.S
  AS      lib/cpus/aarch64/cortex_a35.S
  AS      lib/cpus/aarch64/cortex_a53.S
  AS      lib/cpus/aarch64/cortex_a57.S
  AS      lib/cpus/aarch64/cortex_a72.S
  AS      lib/cpus/aarch64/cortex_a73.S
  AS      lib/cpus/aarch64/cpu_helpers.S
  AS      lib/cpus/aarch64/cpuamu_helpers.S
  AS      lib/cpus/aarch64/dsu_helpers.S
  AS      lib/cpus/aarch64/wa_cve_2017_5715_bpiall.S
  AS      lib/cpus/aarch64/wa_cve_2017_5715_mmu.S
  AS      lib/el3_runtime/aarch64/context.S
  AS      lib/el3_runtime/aarch64/cpu_data.S
  AS      lib/extensions/amu/aarch64/amu_helpers.S
  AS      lib/locks/exclusive/aarch64/spinlock.S
  AS      lib/psci/aarch64/psci_helpers.S
  AS      plat/arm/board/fvp/aarch64/fvp_helpers.S
  AS      plat/common/aarch64/platform_mp_stack.S
  AS      common/aarch64/debug.S
  AS      lib/aarch64/cache_helpers.S
  AS      lib/aarch64/misc_helpers.S
  AS      plat/common/aarch64/platform_helpers.S
  AS      drivers/arm/pl011/aarch64/pl011_console.S
  AS      plat/arm/board/common/aarch64/board_arm_helpers.S
  AS      plat/arm/common/aarch64/arm_helpers.S
  AS      lib/xlat_tables_v2/aarch64/enable_mmu.S
  PP      bl31/bl31.ld.S
  LD      /home/caizh/bl-mt798x/atf-20220606-637ba581b/build/fvp/release/bl31/bl31.elf
  BIN     /home/caizh/bl-mt798x/atf-20220606-637ba581b/build/fvp/release/bl31.bin

Built /home/caizh/bl-mt798x/atf-20220606-637ba581b/build/fvp/release/bl31.bin successfully

  OD      /home/caizh/bl-mt798x/atf-20220606-637ba581b/build/fvp/release/bl31/bl31.dump
  CC      plat/arm/board/fvp/fvp_bl2u_setup.c
  CC      drivers/arm/tzc/tzc400.c
  CC      plat/arm/board/fvp/fvp_security.c
  CC      plat/arm/common/arm_tzc400.c
  CC      drivers/delay_timer/delay_timer.c
  CC      drivers/delay_timer/generic_delay_timer.c
  CC      plat/arm/common/arm_bl2u_setup.c
  CC      bl2u/bl2u_main.c
  CC      common/bl_common.c
  CC      common/tf_log.c
  CC      drivers/console/multi_console.c
  CC      plat/common/plat_bl_common.c
  CC      plat/common/plat_log_common.c
  CC      plat/common/aarch64/plat_common.c
  CC      lib/compiler-rt/builtins/popcountdi2.c
  CC      lib/compiler-rt/builtins/popcountsi2.c
  CC      plat/arm/board/fvp/fvp_common.c
  CC      plat/arm/common/arm_common.c
  CC      plat/arm/common/arm_console.c
  CC      lib/xlat_tables_v2/aarch64/xlat_tables_arch.c
  CC      lib/xlat_tables_v2/xlat_tables_context.c
  CC      lib/xlat_tables_v2/xlat_tables_core.c
  CC      lib/xlat_tables_v2/xlat_tables_utils.c
  AS      bl2u/aarch64/bl2u_entrypoint.S
  AS      plat/common/aarch64/platform_up_stack.S
  AS      common/aarch64/early_exceptions.S
  AS      common/aarch64/debug.S
  AS      lib/aarch64/cache_helpers.S
  AS      lib/aarch64/misc_helpers.S
  AS      plat/common/aarch64/platform_helpers.S
  AS      drivers/arm/pl011/aarch64/pl011_console.S
  AS      plat/arm/board/common/aarch64/board_arm_helpers.S
  AS      plat/arm/common/aarch64/arm_helpers.S
  AS      lib/xlat_tables_v2/aarch64/enable_mmu.S
  PP      bl2u/bl2u.ld.S
  LD      /home/caizh/bl-mt798x/atf-20220606-637ba581b/build/fvp/release/bl2u/bl2u.elf
  BIN     /home/caizh/bl-mt798x/atf-20220606-637ba581b/build/fvp/release/bl2u.bin

Built /home/caizh/bl-mt798x/atf-20220606-637ba581b/build/fvp/release/bl2u.bin successfully

  OD      /home/caizh/bl-mt798x/atf-20220606-637ba581b/build/fvp/release/bl2u/bl2u.dump
  CPP     plat/arm/board/fvp/fdts/fvp_fw_config.dts
  DTC     plat/arm/board/fvp/fdts/fvp_fw_config.dts
  CPP     plat/arm/board/fvp/fdts/fvp_tb_fw_config.dts
  DTC     plat/arm/board/fvp/fdts/fvp_tb_fw_config.dts
  CPP     plat/arm/board/fvp/fdts/fvp_soc_fw_config.dts
  DTC     plat/arm/board/fvp/fdts/fvp_soc_fw_config.dts
  CPP     plat/arm/board/fvp/fdts/fvp_nt_fw_config.dts
  DTC     plat/arm/board/fvp/fdts/fvp_nt_fw_config.dts
  CPP     fdts/fvp-base-gicv3-psci.dts
  DTC     fdts/fvp-base-gicv3-psci.dts
/home/caizh/bl-mt798x/atf-20220606-637ba581b/build/fvp/release/fdts/fvp-base-gicv3-psci.pre.dts:128.20-133.5: Warning (simple_bus_reg): /smb@0,0/motherboard/flash@0,00000000: simple-bus unit address format error, expected "0"
/home/caizh/bl-mt798x/atf-20220606-637ba581b/build/fvp/release/fdts/fvp-base-gicv3-psci.pre.dts:134.19-137.5: Warning (simple_bus_reg): /smb@0,0/motherboard/vram@2,00000000: simple-bus unit address format error, expected "200000000"
/home/caizh/bl-mt798x/atf-20220606-637ba581b/build/fvp/release/fdts/fvp-base-gicv3-psci.pre.dts:138.23-142.5: Warning (simple_bus_reg): /smb@0,0/motherboard/ethernet@2,02000000: simple-bus unit address format error, expected "202000000"
/home/caizh/bl-mt798x/atf-20220606-637ba581b/build/fvp/release/fdts/fvp-base-gicv3-psci.pre.dts:143.26-148.5: Warning (simple_bus_reg): /smb@0,0/motherboard/clk24mhz: missing or empty reg/ranges property
/home/caizh/bl-mt798x/atf-20220606-637ba581b/build/fvp/release/fdts/fvp-base-gicv3-psci.pre.dts:149.30-154.5: Warning (simple_bus_reg): /smb@0,0/motherboard/refclk1mhz: missing or empty reg/ranges property
/home/caizh/bl-mt798x/atf-20220606-637ba581b/build/fvp/release/fdts/fvp-base-gicv3-psci.pre.dts:155.32-160.5: Warning (simple_bus_reg): /smb@0,0/motherboard/refclk32khz: missing or empty reg/ranges property
/home/caizh/bl-mt798x/atf-20220606-637ba581b/build/fvp/release/fdts/fvp-base-gicv3-psci.pre.dts:161.21-283.5: Warning (simple_bus_reg): /smb@0,0/motherboard/iofpga@3,00000000: simple-bus unit address format error, expected "300000000"
/home/caizh/bl-mt798x/atf-20220606-637ba581b/build/fvp/release/fdts/fvp-base-gicv3-psci.pre.dts:284.33-290.5: Warning (simple_bus_reg): /smb@0,0/motherboard/fixedregulator: missing or empty reg/ranges property
/home/caizh/bl-mt798x/atf-20220606-637ba581b/build/fvp/release/fdts/fvp-base-gicv3-psci.pre.dts:294.21-300.6: Warning (simple_bus_reg): /smb@0,0/motherboard/mcc/osc: missing or empty reg/ranges property
/home/caizh/bl-mt798x/atf-20220606-637ba581b/build/fvp/release/fdts/fvp-base-gicv3-psci.pre.dts:301.12-304.6: Warning (simple_bus_reg): /smb@0,0/motherboard/mcc/muxfpga: missing or empty reg/ranges property
/home/caizh/bl-mt798x/atf-20220606-637ba581b/build/fvp/release/fdts/fvp-base-gicv3-psci.pre.dts:305.12-308.6: Warning (simple_bus_reg): /smb@0,0/motherboard/mcc/dvimode: missing or empty reg/ranges property
make[1]: Leaving directory '/home/caizh/bl-mt798x/atf-20220606-637ba581b'
make: Leaving directory '/home/caizh/bl-mt798x/atf-20220606-637ba581b'
fip build fail!
`

**Comment by codercaizh** [comment]
> 把完整的日志输出发上来

已经解决了，是系统没有安装python的缘故，其实前面检查出来了，但没有中止，还是继续往下跑了

**Comment by ningsibuqu** [comment]
> 把完整的日志输出发上来

建议可以把去年编译的版本删了，好些人刷成砖头

**Comment by hanwckf** [comment]
> > 把完整的日志输出发上来
> 
> 建议可以把去年编译的版本删了，好些人刷成砖头

已经删除旧的release
