### ISSUE TITLE
MTD device 'nmbm0' not found

### ISSUE THREAD

**Issue by happy42779** [hanwckf/bl-mt798x#3]
您好，

今天刷了最新的uboot，然后按教程从uboot刷入固件，但是怎么都不成功。网页说：Soemthing went wrong during update. 
然后我尝试用途ttl上传然后操作，找到以下错误信息:
![image](https://github.com/hanwckf/bl-mt798x/assets/12154967/c98acbfb-0000-4187-a0b2-0c320dba55a2)

刚刚又捕捉到一个一刷而过的错误：
![image](https://github.com/hanwckf/bl-mt798x/assets/12154967/47fb847b-d32b-4a07-99bb-4076a548089b)

现在有什么办法解决吗？

**Comment by hanwckf** [comment]
请问你这个路由器是360T7么？从日志来看是识别到了一个未知型号的SPI NAND

**Comment by happy42779** [comment]
> 请问你这个路由器是360T7么？从日志来看是识别到了一个未知型号的SPI NAND

是的，我以为github上的uboot也是可以用的，没想到不能用。

**Comment by hanwckf** [comment]
应该是硬件问题，你的路由器cpu硬件损坏了，无法正确识别spi-nand

**Comment by hyaohao** [comment]
新出厂360 T7M使用的SPI NAND是Winbond W25N01KVZEIR，刷Uboot后会出现这个故障提示。

芯片的资料
https://www.winbond.com/hq/product/code-storage-flash-memory/qspinand-flash/?__locale=zh&partNo=W25N01KV

**Comment by hanwckf** [comment]
> 新出厂360 T7M使用的SPI NAND是Winbond W25N01KVZEIR，刷Uboot后会出现这个故障提示。
> 
> 芯片的资料 https://www.winbond.com/hq/product/code-storage-flash-memory/qspinand-flash/?__locale=zh&partNo=W25N01KV

看到了，应该是新的winbind spi nand id，等会准备更新下，可以再试试

**Comment by hanwckf** [comment]
https://github.com/hanwckf/bl-mt798x/commit/8ff6bf1aad2412880c9b7329c6caba9afa609195
