### ISSUE TITLE
XDR608x能否支持驱动2.5G网口？

### ISSUE THREAD

**Issue by seer300** [hanwckf/bl-mt798x#58]
查阅了mt7986a-tplink-tl-xdr608x.dts文件，发现驱动的是mt7531交换芯片，这是否意味着Uboot下只能通过千兆口刷机？
有无办法能支持Uboot下驱动起来2.5G口，来进行刷机？

望大佬解答，谢谢！

**Comment by wulei-student** [comment]
这个有点难，目前只看到过支持en8811 2.5G 芯片的，还没发现支持realtek 2.5G phy的
