### ISSUE TITLE
AX3000T刷入最新release的uboot后无法进入系统和uboot页面

### ISSUE THREAD

**Issue by Pull256** [hanwckf/bl-mt798x#88]

**Comment by Pull256** [comment]
**补充说明，我刷入的是 mt7981_ax3000t-fip-fixed-parts.bin ，刷入过程为**

```
root@XiaoQiang:/tmp# mtd write mt7981_ax3000t-fip-fixed-parts.bin FIP
Unlocking FIP ...

Writing from mt7981_ax3000t-fip-fixed-parts.bin to FIP ...
root@XiaoQiang:/tmp# mtd write mt7981_ax3000t-fip-fixed-parts.bin FIP
Unlocking FIP ...

Writing from mt7981_ax3000t-fip-fixed-parts.bin to FIP ...
root@XiaoQiang:/tmp#
```

刷入后，重启路由器，按reset5秒后，指示灯变蓝，连接网线在4个接口中的每一个，ip设为192.168.31.100，网关192.168.31.1，掩码255.255.255.0，访问192.168.31.1无法连接，ping不通192.168.31.1。
更换ip为192.168.1.*，192.168.2.*均无法进入uboot。
直接开机后，原厂系统无法进入，插入网线显示ip169.254网段，指示灯橙色。无wifi信号发射。

**Comment by Forgo7ten** [comment]
我刚刷……刷完就看见你issue了。
我是AX6000，刷入之后进不了uboot，但是我原系统能进……就又进去刷了一下uboot

**Comment by Pull256** [comment]
我在怀疑是不是小米改了啥导致的，主要是刷入一些正常，为了保证结果我还刷了两次，理论上不至于啊。

**Comment by Forgo7ten** [comment]
> 我在怀疑是不是小米改了啥导致的，主要是刷入一些正常，为了保证结果我还刷了两次，理论上不至于啊。

之前我用的22.7版本的没问题，这次刷的release最新的23.7，就进不了uboot。
进原系统我还校验了一下FIP刷的是正确的。感觉像是uboot的问题。

但是release这么久了没有人提issue...可能是我的问题叭... 我老老实实用22.7r3版叭

**Comment by Pull256** [comment]
更新下细节，今天刷了[https://www.blumia.net/2024/05/25/ax3000t-uboot-immortalwrt.html](https://www.blumia.net/2024/05/25/ax3000t-uboot-immortalwrt.html)编译的[uboot](https://github.com/BLumia/bl-mt798x/tree/24.05.25)，能进入原始系统，但是还是进不去uboot。我核对了下某个售卖uboot的下的评论区，有9月的评论表示，出厂固件是1.0.84的路由器在刷机后会出现无法识别网线的问题，不知道是不是指uboot无法访问。
所以如果像我一样近期买的话，请核对出厂固件是否为*1.0.84*，如果是，请谨慎刷机，至少不要刷24年1月这个release的，现在我还找不到救砖的方法。

**Comment by Pull256** [comment]
我仔细学习和查看了openwrt对该设备的[刷机教程](https://openwrt.org/inbox/toh/xiaomi/ax3000t#installation)以及[论坛页面](https://forum.openwrt.org/t/openwrt-support-for-xiaomi-ax3000t/180490/1147)，对上述内容进行补充
1、出厂固件为1.0.84的路由器在降级至1.0.47后，网线接口会无法使用，这在我之前的尝试中发现了，但我并未注意。
2、上述问题会导致uboot无法通过网线接口访问
3、Openwrt官方表示目前无法支持新路由器所带的AN8855硬件，需要等待

**Comment by Ser9ei** [comment]
> 3、Openwrt官方表示目前无法支持新路由器所带的AN8855硬件，需要等待

And the new an8855 switch should also be supported in u-boot.
Now, an8855 driver not included in this bootloader. 
https://git01.mediatek.com/plugins/gitiles/openwrt/feeds/mtk-openwrt-feeds/+/ac95e9fe1b014ad01c18256465f6519696858fbf

Perhaps this issue should be renamed to 'add support for an8855 switch'.

**Comment by bh4gaf** [comment]
> 更新下细节，今天刷了https://www.blumia.net/2024/05/25/ax3000t-uboot-immortalwrt.html编译的[uboot](https://github.com/BLumia/bl-mt798x/tree/24.05.25)，能进入原始系统，但是还是进不去uboot。我核对了下某个售卖uboot的下的评论区，有9月的评论表示，出厂固件是1.0.84的路由器在刷机后会出现无法识别网线的问题，不知道是不是指uboot无法访问。
> 所以如果像我一样近期买的话，请核对出厂固件是否为_1.0.84_，如果是，请谨慎刷机，至少不要刷24年1月这个release的，现在我还找不到救砖的方法。

我也这样了，请问你怎么再次刷的？我已经既进不了UBOOT，也进不了原始系统。等于是变砖了

**Comment by bh4gaf** [comment]
> I confirm, this Bootloader will not work on the router on which 1.0.84 version of firmware was installed. See reason above - new an8855 switch.

How to debrick

**Comment by Ser9ei** [comment]
> How to debrick

SPI-NAND programmer or mtk_uartboot method (method for developers)
I like the second, this method was described on the OpenWrt forum.

Boot your with help bootloader from the RAM and replace the bootloader with the stock u-boot (and maybe is necessary return stock firmware or install OpenWrt for the stock layout)

See more details by the link
https://forum.openwrt.org/t/openwrt-support-for-xiaomi-ax3000t/180490/420

**Comment by bietiaop** [comment]
> > 更新下细节，今天刷了[https://www.blumia.net/2024/05/25/ax3000t-uboot-immortalwrt.html编译的[uboot](https://github.com/BLumia/bl-mt798x/tree/24.05.25)，能进入原始系统，但是还是进不去uboot。我核对了下某个售卖uboot的下的评论区，有9月的评论表示，出厂固件是1.0.84的路由器在刷机后会出现无法识别网线的问题，不知道是不是指uboot无法访问。](https://www.blumia.net/2024/05/25/ax3000t-uboot-immortalwrt.html%E7%BC%96%E8%AF%91%E7%9A%84%5Buboot%5D(https://github.com/BLumia/bl-mt798x/tree/24.05.25)%EF%BC%8C%E8%83%BD%E8%BF%9B%E5%85%A5%E5%8E%9F%E5%A7%8B%E7%B3%BB%E7%BB%9F%EF%BC%8C%E4%BD%86%E6%98%AF%E8%BF%98%E6%98%AF%E8%BF%9B%E4%B8%8D%E5%8E%BBuboot%E3%80%82%E6%88%91%E6%A0%B8%E5%AF%B9%E4%BA%86%E4%B8%8B%E6%9F%90%E4%B8%AA%E5%94%AE%E5%8D%96uboot%E7%9A%84%E4%B8%8B%E7%9A%84%E8%AF%84%E8%AE%BA%E5%8C%BA%EF%BC%8C%E6%9C%899%E6%9C%88%E7%9A%84%E8%AF%84%E8%AE%BA%E8%A1%A8%E7%A4%BA%EF%BC%8C%E5%87%BA%E5%8E%82%E5%9B%BA%E4%BB%B6%E6%98%AF1.0.84%E7%9A%84%E8%B7%AF%E7%94%B1%E5%99%A8%E5%9C%A8%E5%88%B7%E6%9C%BA%E5%90%8E%E4%BC%9A%E5%87%BA%E7%8E%B0%E6%97%A0%E6%B3%95%E8%AF%86%E5%88%AB%E7%BD%91%E7%BA%BF%E7%9A%84%E9%97%AE%E9%A2%98%EF%BC%8C%E4%B8%8D%E7%9F%A5%E9%81%93%E6%98%AF%E4%B8%8D%E6%98%AF%E6%8C%87uboot%E6%97%A0%E6%B3%95%E8%AE%BF%E9%97%AE%E3%80%82)
> > 所以如果像我一样近期买的话，请核对出厂固件是否为_1.0.84_，如果是，请谨慎刷机，至少不要刷24年1月这个release的，现在我还找不到救砖的方法。
> 
> 我也这样了，请问你怎么再次刷的？我已经既进不了UBOOT，也进不了原始系统。等于是变砖了

请问有解决方案了吗 现在啥也做不了

**Comment by HuangRicky** [comment]
看上去是因为小米路由器有了新的一批v2版本，看这里 https://www.right.com.cn/forum/thread-8301127-1-1.html
他们的交换机芯片不一样了，所以之前的uboot刷入后，就识别不了任何网口。 但是我现在可以进原始系统，没有变砖。我理解的是需要修改过的uboot.. 恩山上的那个人提供了360t7的新uboot但是没有xiaomi3000t的。。请@hanwckf 大神看看能否帮我们制作一个fix过的uboot。。。谢谢！

**Comment by hanwckf** [comment]
已经适配好了，重新拉取源码，使用ax3000t_an8855这个型号编译就可以了

**Comment by HuangRicky** [comment]
> 已经适配好了，重新拉取源码，使用ax3000t_an8855这个型号编译就可以了

感谢您，已经编译好刷进去了！果然可以用了！

**Comment by bh4gaf** [comment]
> 已经适配好了，重新拉取源码，使用ax3000t_an8855这个型号编译就可以了


我这种进不了系统的怎么办

**Comment by hanwckf** [comment]
> > 已经适配好了，重新拉取源码，使用ax3000t_an8855这个型号编译就可以了
> 
> 我这种进不了系统的怎么办

使用mtk_uartboot插串口进行救砖操作

**Comment by eatnt** [comment]
> > 已经适配好了，重新拉取源码，使用ax3000t_an8855这个型号编译就可以了
> 
> 感谢您，已经编译好刷进去了！果然可以用了！
你好，可以把编译好的给我发一下吗？谢谢1821170167@qq.com
